---
title: "Introduction to Analyzing NCES Data Using EdSurvey"
author: "Developed by Paul Bailey, Charles Blankenship, Eric Buehler, Ren C'deBaca, Nancy Collins, Ahmad Emad, Thomas Fink,  Huade Huo, Frank Fonseca, Julian Gerez, Sun-joo Lee, Michael Lee, Jiayi Li, Yuqi Liao, Alex Lishinski, Thanh Mai, Trang Nguyen, Emmanuel Sikali, Qingshu Xie, Sinan Yavuz, Jiao Yu, and Ting Zhang"
date: "`r gsub(' 202',', 202', format(Sys.Date(), format='%B %d %Y'))`"
output:
  html_document: default
vignette: |
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{EdSurvey}
---
  
# Overview of the EdSurvey Package
  
The `EdSurvey` package is designed to help users analyze data from the National Center for Education Statistics (NCES), including the National Assessment of Educational Progress (NAEP) datasets. Because of their scope and complexity, these datasets require special statistical methods to analyze. The `EdSurvey` package gives users functions to perform analyses that account for both complex sample survey designs and the use of plausible values.

The `EdSurvey` package also seamlessly takes advantage of the `LaF` package to read in data only when it is required for an analysis. Users with computers that have insufficient memory to read in the entire NAEP datasets can still do analyses without having to write special code to read in just the appropriate variables. This is all addressed directly in the `EdSurvey` package---behind the scenes and without additional work by the user.

# Book

Please see our book, [Analyzing NCES Data Using EdSurvey: A User's Guide](https://naep-research.airprojects.org/portals/0/edsurvey_a_users_guide/_book/index.html). Please refer to the book for further information about installing, using, and understanding the statistical methodology in EdSurvey.
 
# Journal Publications

Bailey, P., Lee, M., Nguyen, T., & Zhang, T. (2020). [*Using EdSurvey to Analyse PIAAC Data*](https://link.springer.com/content/pdf/10.1007/978-3-030-47515-4_9.pdf). In *Large-Scale Cognitive Assessment* (pp. 209-237). Springer, Cham.

